### PR TITLE
add es build step

### PR DESCRIPTION
**Pull request by ayal**

### CODE REVIEW

**Comment by rolandjitsu** [comment]
Is this ready for review? It's marked as draft now.

**Comment by okonet** [comment]
It also feels like it’s time to go monorepo but let’s merge it to fix the breakage first.

**Comment by ayal** [comment]
@rolandjitsu @okonet As you can see I upgraded babel / webpack, as used here: https://github.com/react-dropzone/react-dropzone/blob/master/package.json, not sure if you want to try resolving it with the current stack and minimal change, for the least possible friction.

**Comment by rolandjitsu** [comment]
> It also feels like it’s time to go monorepo but let’s merge it to fix the breakage first.

I agree. It makes sense to merge all 3 repos.

**Pull request merged**
