### PR TITLE
Fix TypeScript type definitions

### LINKED ISSUE #29: use : var accept = require('attr-accept');     accept()   accept is not a function
use : var accept = require('attr-accept');     
then:  accept()   
result:  accept is not a function  

solution:   import  accept from 'attr-accept' ????

### PR DESCRIPTION
**Pull request by remcohaszing**
**What kind of change does this PR introduce?**
- [x] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**
The main entrypoint of this package exports a function using `module.exports = …`. The correct type for this is `export = …`.

**Does this PR introduce a breaking change?**
No

**Other information**

Fixes #29

### CODE REVIEW

**Comment by okonet** [comment]
This only changes the types. Is this really solves the problem with CJS? Could we have a test added?

**Comment by remcohaszing** [comment]
Sorry, my bad. I misunderstood the issue. This package does use `module.exports.default` instead of `module.exports`. Although I recommend against doing that, the types are correct.

**Comment by okonet** [comment]
I'm happy to accept a PR that solves the root cause.

**Comment by remcohaszing** [comment]
How to solve the root cause depends on how you want the library to work. It’s going to be breaking anyway, so a semver major would be needed.

Do you want to keep dual publishing? If not, do you want CJS or ESM? If yes, the simplest solution is to switch to a named exports.

**Comment by okonet** [comment]
Would names exports solve the problem? I'd be happy to go with this one. 

How much value dual publishing brings in 2024?

**Comment by remcohaszing** [comment]
> How much value dual publishing brings in 2024?

It really depends on who you ask.

I think the whole dual module system situation is a weird situation that we as the JavaScript community should try to get rid of. Personally I believe the only way to do this, is by pushing forward for ESM-only. There are also some projects that can only consume ESM, but CJS, but that’s relatively rare.

There are still a lot of projcts using CJS. For them it’s really convenient to be able to use `require('attr-accept')` instead of using an asynchronous dynamic import. Node.js 22 has experimental support of `require()`ing ESM as well, so in the future that will likely be possible.

You could dual publish to please everyone. Unfortunately that means you have a build step and you need to be careful about compatibility. When dual publishing you should be careful about the [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard), though that’s not a problem for `attr-accept`.

The best overview of the state of CJS vs ESM can be seen [here](https://github.com/wooorm/npm-esm-vs-cjs#data). So among popular packages, CJS is still used more, but ESM is gaining traction. This includes old packages that may be unmaintained and are stuck on CJS forever.

ESM vs CJS usage

---

> Would names exports solve the problem? I'd be happy to go with this one.

CJS only allows exporting one member, whereas ESM allows exporting multiple members. Default exports make it extra weird, because how do you make an ESM default export compatible with CJS, if the ESM version could potentially export additional named members?

Named exports solve this, because it’s obvious the CJS export is an object that can be destructured nicely.

Also I think nowadays named exports are just generally more popular than default exports, but I don’t have numbers for that.

**Comment by okonet** [comment]
I feel the same way so I'd be happy to get a PR that would be ESM only.

**Pull request closed without merging**
